#!/bin/bash
source grade_utils
run_in_folder_if_exists "solution"

printf "\n\n*** Grade Ancestor-Tree Part B *** \n\n"

make -f Makefile clean
call make -f Makefile test
call timeout 3 ./test
make -f Makefile --silent clean
